Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 55, in main
    manager.start_session()
  File "main.py", line 41, in start_session
    timeout = self.profile.get_timeout()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 25, in get_timeout
    return int(self.data["timeout"])
               ~~~~~~~~~^^^^^^^^^^^
KeyError: 'timeout'